Add support for optional attributes
bergundy/tjs-methods pull request #4
Opened 2018-08-26 15:43 UTC by vogre

Added a single unittest

2018-08-30 07:07 UTC, bergundy requested changes
Thanks!
Please also change the generated server code.

2018-08-30 07:07 UTC, bergundy commented on src/test_rpc.ts
> +      c: string | undefined;
please test optional params (`c?: string`), this case already works without the fix

2018-08-30 07:07 UTC, bergundy commented on templates/ts/server.ts
> +      const sortedArgs = order.map(param => coerced[param]);
Like!

2019-02-03 16:37 UTC, vogre commented
@bergundy : PTAL, also changed the server code.

2019-02-04 17:07 UTC, bergundy approved these changes
Thanks!

2019-02-04 17:07 UTC, bergundy commented on src/test/test_rpc.ts
> + expect(await client.bar('hello', 3, undefined, undefined)).to.equal('3');
Could have been tested with parameters omitted.

2019-02-04 17:14 UTC, merged